version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: sunday
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    open-pull-requests-limit: 10
    labels:
      - 'type: dependency-upgrade'
    groups:
       development-dependencies:
         update-types:
          - patch
         patterns:
           - com.gradle*
           - org.asciidoctor*
           - com.jfrog.artifactory
           - com.diffplug.spotless
           - org.powermock*
           - org.awaitility:awaitility
           - org.testcontainers*
           - com.google.code.findbugs:jsr305
           - junit:junit
           - org.assertj:assertj-core
           - org.apache.logging.log4j*
           - org.slf4j:slf4j-api
           - io.micrometer:micrometer-tracing-integration-test

  - package-ecosystem: gradle
    target-branch: 1.3.x
    directory: /
    schedule:
      interval: weekly
      day: sunday
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    open-pull-requests-limit: 10
    labels:
      - 'type: dependency-upgrade'
    groups:
      development-dependencies:
        update-types:
          - patch
        patterns:
          - com.gradle*
          - org.asciidoctor*
          - com.jfrog.artifactory
          - com.diffplug.spotless
          - org.powermock*
          - org.awaitility:awaitility
          - org.testcontainers*
          - com.google.code.findbugs:jsr305
          - junit:junit
          - org.assertj:assertj-core
          - org.apache.logging.log4j*
          - org.slf4j:slf4j-api
          - io.micrometer:micrometer-tracing-integration-test

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
    labels:
      - 'type: task'
    groups:
      development-dependencies:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    target-branch: 1.3.x
    directory: /
    schedule:
      interval: weekly
      day: sunday
    labels:
      - 'type: task'
    groups:
      development-dependencies:
        patterns:
          - '*'
