version: 2
updates:
  - package-ecosystem: gradle
    target-branch: 1.3.x
    directory: /
    schedule:
      interval: weekly
      day: sunday
    allow:
      - dependency-name: org.apache.kafka:kafka-clients
      - dependency-name: io.micrometer:micrometer-core
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    open-pull-requests-limit: 10
    labels:
      - 'type/dependency-upgrade'

  - package-ecosystem: gradle
    target-branch: 1.3.x
    directory: /
    schedule:
      interval: weekly
      day: sunday
    ignore:
      - dependency-name: '*'
    open-pull-requests-limit: 10
    labels:
      - 'type/chores'
    groups:
      development-dependencies:
        update-types:
          - patch
        patterns:
          - com.gradle*
          - org.asciidoctor*
          - com.jfrog.artifactory
          - com.diffplug.spotless
          - org.powermock*
          - org.awaitility:awaitility
          - org.testcontainers*
          - junit:junit
          - org.assertj:assertj-core
          - org.apache.logging.log4j*
          - org.slf4j:slf4j-api
          - io.micrometer:micrometer-tracing-integration-test
          - io.projectreactor*

  - package-ecosystem: github-actions
    target-branch: 1.3.x
    directory: /
    schedule:
      interval: weekly
      day: sunday
    labels:
      - 'type/chores'
    groups:
      development-dependencies:
        patterns:
          - '*'
